language: cpp
script:
#get libsecp256k1
- git clone https://github.com/bitcoin-core/secp256k1.git
- cd secp256k1
- ./autogen.sh
- ./configure --enable-module-recovery
- make && sudo make install
#build
- cmake -S . -B_build
- cmake --build _build
