
sudo: false

dist: xenial
language: cpp
addons:
  apt:
    packages:
    - libboost-system-dev
    - libboost-thread-dev
    - doxygen

install:
#get libsecp256k1
  - git clone https://github.com/bitcoin-core/secp256k1.git
  - cd secp256k1
  - ./autogen.sh
  - ./configure --enable-module-recovery
  - make && sudo make install
  - cd -
#get json_spirit
  - git clone https://github.com/smlee-hdactech/json_spirit.git
  - cd json_spirit
  - cmake -S . -B_build
  - cmake --build _build
  - sudo make install -C_build  
  - cd -
script:  
#build
  - cmake -S . -B_build
  - cmake --build _build
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
